Document: solvespace
Title: Debian solvespace Manual
Author: <insert document author here>
Abstract: This manual describes what solvespace is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/solvespace/solvespace.sgml.gz

Format: postscript
Files: /usr/share/doc/solvespace/solvespace.ps.gz

Format: text
Files: /usr/share/doc/solvespace/solvespace.text.gz

Format: HTML
Index: /usr/share/doc/solvespace/html/index.html
Files: /usr/share/doc/solvespace/html/*.html
